sudo: required
services:
  - docker
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
install:
  - composer self-update
  - composer install
script: 
  - phpunit --configuration phpunit.xml
  - phpunit BuzzBoardTestClient.php
  - phpunit BuzzBoardTestCategories.php