language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  
before_script:
  - composer self-update
  - composer update
sudo: required
before_install:
  - php /home/travis/.phpenv/versions/5.4/bin/composer.phar self-update
  - php /home/travis/.phpenv/versions/5.4/bin/composer.phar update