sudo: required
services:
  - docker
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly  
before_script:
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - /home/travis/.phpenv/versions/5.4/bin/composer update
env:
  - TESTFOLDER=tests
install:
  - /home/travis/.phpenv/versions/5.4/bin/composer install